### ISSUE TITLE
Show Wallet / MM login status / Network on Landing page

### ISSUE THREAD

**Issue by oznekenzo** [uport-project/3box-dapp#123]
Arguably a better UX to show the status of these requirements for logging in to 3Box before they click sign in or create profile

**Comment by oznekenzo** [comment]
![web3check](https://user-images.githubusercontent.com/8059373/48511881-01b76e80-e826-11e8-8949-7a6211643de1.png)
![web3check1](https://user-images.githubusercontent.com/8059373/48511888-0419c880-e826-11e8-9483-b485e93b07e8.png)

**Comment by oznekenzo** [comment]
@michaelsena - here are initial designs - just exploring what might be cool, not necessarily a priority.
Maybe the "Web3 Check" plugin could be another cool lightweight utility from 3Box that other dapps can use to help web3 users with onboarding and understanding web3.

**Comment by michaelsena** [comment]
@oznekenzo if I'm understanding correctly, this feature is meant to solve the problem of users clicking sign in and *then* being told they need to "Sign in or unlock MetaMack to continue?"

As much as I like this feature, wondering if there is a more simplified design implementation that is always visible. Since this design hides information behind a hover link, it doesn't provide that much additional benefit to me the user as compared to being told this after I click sign in. 

I would prefer reusing the "Edit Profile" blue announcement bar under the white navbar and display the text: "Sign in or unlock MetaMack to continue" or "Download MetaMask to continue" <button> or whatever info we can display from the info you're showing from the card above.

Also, if this take a long time I'm not sure this is super high priority.

**Comment by oznekenzo** [comment]
@michaelsena Yeah that's correct.
And yeah I agree with you, there is a way to simplify this design - I'm working now on having these pieces of information being exposed from the beginning - will work on the blue announcement bar that you've mentinoed above.  Don't think it will take too long so we can drop it if we need to.

**Comment by oznekenzo** [comment]
![banner](https://user-images.githubusercontent.com/8059373/48566327-88bd2300-e8c8-11e8-8916-8c56673944fc.png)

**Comment by oznekenzo** [comment]
This simple banner dialogue at the top would appear only if 3Box detects a user has no wallet at all.  With the new breaking change, we cannot differentiate between not being logged in to MetaMask and being logged in but yet to provide consent.  I've added the network data next to the 3Box logo to the interface - previously this only showed after logging in.  Not priority as you mentioned but perhaps would improve UX incrementally.

**Comment by michaelsena** [comment]
I think the banner at the top is a good idea for users that have no wallet installed. Let's make it more clear that it will direct them to MetaMask: "3Box requires a web3-enabled wallet. We recommend MetaMask. <Get it here> <- Button

I don't think we should include the network ID badge on the homepage. If the user's MM is set to Ropsten (and they forget), and then they come to 3box.io and see "Ropsten" there then they will think that our app is currently on Ropsten... and not think that it's their network setting. We should keep user network ID info inside of the dapp experience. @oznekenzo

**Comment by oznekenzo** [comment]
Screen shot of implementation
<img width="1484" alt="screen shot 2018-11-20 at 9 56 57 am" src="https://user-images.githubusercontent.com/8059373/48781786-b8926f00-ecaa-11e8-966b-cca4edb834ef.png">

**Comment by michaelsena** [comment]
@oznekenzo on mobile we should still be showing the other modal with Coinbase Wallet and Trust Wallet. Instead now we are showing the new bar. Can we please update this to not appear on mobile? Ty!

**Comment by oznekenzo** [comment]
Fixed! @michaelsena

**Comment by michaelsena** [comment]
Looks good @oznekenzo thanks!
