### ISSUE TITLE
Add network id badge to app header

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-dapp#97]
Currently we do not display which network the user is on in our app. It would be helpful for the user to know which network they're currently on when using our application. Bounties.network, for example, does a good job of this by adding a simple network id badge in their header.

**Comment by oznekenzo** [comment]
@michaelsena we had the design scoped for the network to appear in the user profile section on the activity page but I think it would be best to follow the same pattern as Bounties.network and display that in the nav so that users can expect to see that info consistently in the same place - what do you think?  Will implement tomorrow
